### ISSUE TITLE
VPython diagnostic messages

### ISSUE THREAD

**Issue by petercorke** [petercorke/robotics-toolbox-python#192]
This is recent with VPython, this message occurs a few times, but is not fatal

```
Exception happened during processing of request from ('127.0.0.1', 56701)
Traceback (most recent call last):
  File "/Users/corkep/opt/miniconda3/envs/dev/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Users/corkep/opt/miniconda3/envs/dev/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/Users/corkep/opt/miniconda3/envs/dev/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/corkep/opt/miniconda3/envs/dev/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/Users/corkep/opt/miniconda3/envs/dev/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/Users/corkep/opt/miniconda3/envs/dev/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/Users/corkep/opt/miniconda3/envs/dev/lib/python3.8/site-packages/vpython/no_notebook.py", line 124, in do_GET
    fd = open(loc, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/corkep/opt/miniconda3/envs/dev/lib/python3.8/site-packages/vpython/vpython_libraries/apple-touch-icon.png'
```

On a quick google skim I find mentions to this icon file, but nothing that is VPython specific.

**Comment by petercorke** [comment]
Hmm, they just stopped happening...
