### ISSUE TITLE
patch for the Robot.py file

### ISSUE THREAD

**Issue by asmwarrior** [petercorke/robotics-toolbox-python#216]
Hi, with the latest github master version, I have to use this changes:

~~~~
 roboticstoolbox/robot/Robot.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/roboticstoolbox/robot/Robot.py b/roboticstoolbox/robot/Robot.py
index e47a159e..2d3efb00 100644
--- a/roboticstoolbox/robot/Robot.py
+++ b/roboticstoolbox/robot/Robot.py
@@ -1304,9 +1304,9 @@ class Robot(ABC, DynamicsMixin, IKMixin):
         # Add the self to the figure in readonly mode
         # Add the self to the figure in readonly mode
         if q.shape[0] == 1:
-            env.launch(self.name + ' Plot', limits=limits, fig=fig)
+            env.launch(name = self.name + ' Plot', limits=limits, fig=fig)
         else:
-            env.launch(self.name + ' Trajectory Plot', limits=limits, fig=fig)
+            env.launch(name = self.name + ' Trajectory Plot', limits=limits, fig=fig)
 
         env.add(
             self, readonly=True, jointaxes=jointaxes, jointlabels=jointlabels,

~~~~

Otherwise, I will get an error saying that:

~~~~
Traceback (most recent call last):

  File "e:\code\robotics\robotics-toolbox-python\roboticstoolbox\examples\puma_jtraj.py", line 51, in <module>
    robot.plot(qt.q, backend=args.backend)

  File "e:\code\robotics\robotics-toolbox-python\roboticstoolbox\robot\Robot.py", line 1309, in plot
    env.launch(self.name + ' Trajectory Plot', limits=limits, fig=fig)

TypeError: launch() takes 1 positional argument but 2 were given
~~~~

**Comment by petercorke** [comment]
There's been a lot of overlapping changes, so I'll pass on this one
