### ISSUE TITLE
Could not use the spatialmath-python module

### ISSUE THREAD

**Issue by liuyang-664** [petercorke/robotics-toolbox-python#354]
When I run the tests/test_mobile.py file, there is an Error saying " model 'spatialmath' has no attribute 'base' ". 
I used 'pip3 install roboticstoolbox-python' to install the module, and successfully installed spatialmath-python-1.0.5.

Does anyone know how to solve this? Appreciate your answer very much.

## Error Information
Traceback (most recent call last):
  File "tests/test_mobile.py", line 7, in <module>
    import roboticstoolbox as rtb
  File "/home/jeremy/.local/lib/python3.6/site-packages/roboticstoolbox/__init__.py", line 1, in <module>
    from roboticstoolbox.tools import *
  File "/home/jeremy/.local/lib/python3.6/site-packages/roboticstoolbox/tools/__init__.py", line 2, in <module>
    from roboticstoolbox.tools.p_servo import p_servo, angle_axis
  File "/home/jeremy/.local/lib/python3.6/site-packages/roboticstoolbox/tools/p_servo.py", line 4, in <module>
    from spatialmath import SE3, base
  File "/home/jeremy/.local/lib/python3.6/site-packages/spatialmath/__init__.py", line 1, in <module>
    from spatialmath.pose2d import SO2, SE2
  File "/home/jeremy/.local/lib/python3.6/site-packages/spatialmath/pose2d.py", line 26, in <module>
    from spatialmath.base import argcheck
  File "/home/jeremy/.local/lib/python3.6/site-packages/spatialmath/base/__init__.py", line 7, in <module>
    from spatialmath.base.transforms2d import *  # lgtm [py/polluting-import]
  File "/home/jeremy/.local/lib/python3.6/site-packages/spatialmath/base/transforms2d.py", line 20, in <module>
    import spatialmath.base as smb
AttributeError: module 'spatialmath' has no attribute 'base'

## Install Information
Successfully installed ansitable-0.9.7 colored-1.4.4 cycler-0.11.0 kiwisolver-1.3.1 matplotlib-3.3.4 numpy-1.19.5 pgraph-python-0.6.2 pillow-8.4.0 progress-1.6 pyparsing-3.0.9 python-dateutil-2.8.2 roboticstoolbox-python-1.0.2 rtb-data-1.0.0 scipy-1.5.4 six-1.16.0 spatialgeometry-1.0.1 spatialmath-python-1.0.5 swift-sim-1.0.0 websockets-9.1

**Comment by liuyang-664** [comment]
I fixed this problem by replacing "import spatialmath.base as smb" with "from spatialmath import base as smb" in the file 'transforms2d.py'.
