### ISSUE TITLE
Singular inertia matrix for UR5 robot

### ISSUE THREAD

**Issue by DavidUmsonst** [petercorke/robotics-toolbox-python#387]
**Bug description**

Hi everyone, 
I tried to get the script [dynamics.py](https://github.com/petercorke/robotics-toolbox-python/blob/master/notebooks/dynamics.py) to run with a UR5 robot arm instead of the Puma 560 arm.

However, when running the fdyn() function I obtain the following error:  _numpy.linalg.LinAlgError: Singular matrix_
The reason for that seems to be that the inertia function of the UR5 robot from the DH model returns a singular matrix. As far as I know the inertia matrix should be a positive definite matrix and, therefore, non-singular.

Hence, I feel like there is something wrong with how the inertia matrix is calculated for the UR5 robot or I might have implemented something incorrectly.

I saw already that Universal Robots does not provide inertia but mass information for the UR5 robot, so maybe that is the problem.

**Version information**
For the script below I use version 1.1.0 of the Robotics Toolbox for Python

**To Reproduce**
Below you can find the code that reproduces the error:

```
import numpy as np
import roboticstoolbox as rtb
np.set_printoptions(linewidth=100, formatter={'float': lambda x: f"{x:8.4g}" if x > 1e-10 else f"{0:8.4g}"})

UR5 = rtb.models.DH.UR5()

M=UR5.inertia(UR5.qr)
print(f"Inertia matrix: \n {M}")
print(f"Inertia matrix determinant: {np.linalg.det(M)}")

UR5nf = UR5.nofriction()
tg = UR5nf.fdyn(5, UR5.qr, dt=0.05,progress=True)
```

The output of the script is the following:
```
Inertia matrix: 
 [[   3.371  0.01693  0.01693  0.01693        0        0]
 [ 0.01693    3.244    1.277   0.0438        0        0]
 [ 0.01693    1.277   0.5837  0.02879        0        0]
 [ 0.01693   0.0438  0.02879  0.01494        0        0]
 [       0        0        0        0 0.001574        0]
 [       0        0        0        0        0        0]]
Inertia matrix determinant: 0.0
Traceback (most recent call last):
  File "/home/david/rtb-test/DynamicsForBugReporting.py", line 12, in <module>
    tg = UR5nf.fdyn(5, UR5.qr, dt=0.05,progress=True)
  File "/home/david/rtb-test/.venv/lib/python3.10/site-packages/roboticstoolbox/robot/Dynamics.py", line 326, in fdyn
    integrator = scipy_integrator(
  File "/home/david/rtb-test/.venv/lib/python3.10/site-packages/scipy/integrate/_ivp/rk.py", line 94, in __init__
    self.f = self.fun(self.t, self.y)
  File "/home/david/rtb-test/.venv/lib/python3.10/site-packages/scipy/integrate/_ivp/base.py", line 138, in fun
    return self.fun_single(t, y)
  File "/home/david/rtb-test/.venv/lib/python3.10/site-packages/scipy/integrate/_ivp/base.py", line 20, in fun_wrapped
    return np.asarray(fun(t, y), dtype=dtype)
  File "/home/david/rtb-test/.venv/lib/python3.10/site-packages/roboticstoolbox/robot/Dynamics.py", line 327, in <lambda>
    lambda t, y: self._fdyn(t, y, Q, Q_args),
  File "/home/david/rtb-test/.venv/lib/python3.10/site-packages/roboticstoolbox/robot/Dynamics.py", line 422, in _fdyn
    qdd = self.accel(q, qd, tau)
  File "/home/david/rtb-test/.venv/lib/python3.10/site-packages/roboticstoolbox/robot/Dynamics.py", line 507, in accel
    qdd[k, :] = np.linalg.solve(M, tauk - tau)
  File "<__array_function__ internals>", line 200, in solve
  File "/home/david/rtb-test/.venv/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 386, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/home/david/rtb-test/.venv/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
```

**Expected behavior**
The inertia matrix should be a positive definite matrix, which should prevent the singular matrix error thrown by NumPy.

**Environment**
I'm using Ubuntu 22.04 in WSL2 on Windows 10 and my Python version is 3.10.6.

Best regards,
David

**Comment by petercorke** [comment]
Firstly, I'd like to apologise for taking well over three years to get back to you, but essentially my day job and life got in the way. Over the last few months I've been able to devote a lot more time to this toolbox — fixing bugs, reworking dubious design choices, and developing tests and solid CI processes to prevent future drift.

On this specific one: your own instinct was right — I checked the UR5 DH model's own source directly, and it has a literal comment: "mass data, no inertia available". Every link's inertia tensor defaults to zero, so the singular matrix you hit is a data-completeness gap in the bundled model, not a bug in `inertia()` itself. Tracked honestly as #637 (alongside a related UR10 data gap), rather than closed as a fixed bug, since it isn't fixable without someone sourcing real UR5 inertia parameters. Thank you for the clean, minimal repro.
