### ISSUE TITLE
TypeError: Plain typing_extensions.Self is not valid as type argument on Import

### ISSUE THREAD

**Issue by Ptisni** [petercorke/robotics-toolbox-python#388]
**Describe the bug**
Import of roboticstoolbox fails with the error message below.

**Version information**

Did you install from PyPI or GitHub? PyPI
If PyPI what version number? 1.1.0

**To Reproduce**
``
pip install roboticstoolbox-python
ipython3
import roboticstoolbox
``
2. The script output, including error messages.

Traceback (most recent call last):
  File "Controllers.py", line 1, in <module>
    import roboticstoolbox as rtb
  File "/home/peter/.local/lib/python3.8/site-packages/roboticstoolbox/__init__.py", line 3, in <module>
    from roboticstoolbox.robot import *
  File "/home/peter/.local/lib/python3.8/site-packages/roboticstoolbox/robot/__init__.py", line 1, in <module>
    from roboticstoolbox.robot.Robot import BaseRobot, Robot, Robot2
  File "/home/peter/.local/lib/python3.8/site-packages/roboticstoolbox/robot/Robot.py", line 45, in <module>
    from roboticstoolbox.robot.BaseRobot import BaseRobot
  File "/home/peter/.local/lib/python3.8/site-packages/roboticstoolbox/robot/BaseRobot.py", line 43, in <module>
    from roboticstoolbox.robot.Gripper import Gripper
  File "/home/peter/.local/lib/python3.8/site-packages/roboticstoolbox/robot/Gripper.py", line 10, in <module>
    from roboticstoolbox.robot.Link import Link
  File "/home/peter/.local/lib/python3.8/site-packages/roboticstoolbox/robot/Link.py", line 62, in <module>
    class BaseLink(SceneNode, ABC):
  File "/home/peter/.local/lib/python3.8/site-packages/roboticstoolbox/robot/Link.py", line 128, in BaseLink
    parent: Union[Self, str, None] = None,
  File "/usr/lib/python3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.8/typing.py", line 358, in __getitem__
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "/usr/lib/python3.8/typing.py", line 358, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "/usr/lib/python3.8/typing.py", line 145, in _type_check
    raise TypeError(f"Plain {arg} is not valid as type argument")
TypeError: Plain typing_extensions.Self is not valid as type argument

**Environment (please complete the following information):**
 - Your OS (MacOS, Linux, Windows): Ubuntu 20.04
- Your Python version: 3.8.10

**Additional context**

**Comment by petercorke** [comment]
Sorry for the very long wait on this one.

This is a Python 3.8 incompatibility (the `typing_extensions.Self`/`typing` interaction the traceback shows was a real limitation of Python's own `typing` module at that version). roboticstoolbox now requires Python 3.10+ (`pyproject.toml`'s `requires-python`), and Python 3.8 itself reached end-of-life in October 2024 -- so this specific failure can't occur on any currently-supported environment.

Closing as an unsupported/obsolete Python version. If you hit an import error like this on a current Python version (3.10+), please open a fresh issue with the details.
