### ISSUE TITLE
Can't use the swift simulator

### ISSUE THREAD

**Issue by WHuangEI** [petercorke/robotics-toolbox-python#409]
**Check here first**

[Common issues](https://github.com/petercorke/robotics-toolbox-python/wiki/Common-Issues)

**Describe the bug**
when I just run the 'holistic_mm_non_holonomic.py', the browser shows nothing but :
The connection was reset
    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.
and the information in terminal:
$ python holistic_mm_non_holonomic.py 
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45358)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/hwww/.local/lib/python3.6/site-packages/swift/SwiftRoute.py", line 222, in __init__
    *args, directory=str(root_dir), **kwargs
TypeError: __init__() got an unexpected keyword argument 'directory'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45372)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/hwww/.local/lib/python3.6/site-packages/swift/SwiftRoute.py", line 222, in __init__
    *args, directory=str(root_dir), **kwargs
TypeError: __init__() got an unexpected keyword argument 'directory'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45380)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/hwww/.local/lib/python3.6/site-packages/swift/SwiftRoute.py", line 222, in __init__
    *args, directory=str(root_dir), **kwargs
TypeError: __init__() got an unexpected keyword argument 'directory'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45390)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/hwww/.local/lib/python3.6/site-packages/swift/SwiftRoute.py", line 222, in __init__
    *args, directory=str(root_dir), **kwargs
TypeError: __init__() got an unexpected keyword argument 'directory'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45394)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/hwww/.local/lib/python3.6/site-packages/swift/SwiftRoute.py", line 222, in __init__
    *args, directory=str(root_dir), **kwargs
TypeError: __init__() got an unexpected keyword argument 'directory'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45408)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/hwww/.local/lib/python3.6/site-packages/swift/SwiftRoute.py", line 222, in __init__
    *args, directory=str(root_dir), **kwargs
TypeError: __init__() got an unexpected keyword argument 'directory'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45410)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/hwww/.local/lib/python3.6/site-packages/swift/SwiftRoute.py", line 222, in __init__
    *args, directory=str(root_dir), **kwargs
TypeError: __init__() got an unexpected keyword argument 'directory'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45412)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/hwww/.local/lib/python3.6/site-packages/swift/SwiftRoute.py", line 222, in __init__
    *args, directory=str(root_dir), **kwargs
TypeError: __init__() got an unexpected keyword argument 'directory'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45418)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/hwww/.local/lib/python3.6/site-packages/swift/SwiftRoute.py", line 222, in __init__
    *args, directory=str(root_dir), **kwargs
TypeError: __init__() got an unexpected keyword argument 'directory'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45432)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/hwww/.local/lib/python3.6/site-packages/swift/SwiftRoute.py", line 222, in __init__
    *args, directory=str(root_dir), **kwargs
TypeError: __init__() got an unexpected keyword argument 'directory'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45440)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/hwww/.local/lib/python3.6/site-packages/swift/SwiftRoute.py", line 222, in __init__
    *args, directory=str(root_dir), **kwargs
TypeError: __init__() got an unexpected keyword argument 'directory'
----------------------------------------
[ERROR glean_core] Error setting metrics feature config: Json(Error("EOF while parsing a value", line: 1, column: 0))

Could not connect to the Swift simulator 

Traceback (most recent call last):
  File "holistic_mm_non_holonomic.py", line 92, in <module>
    env.launch(realtime=True)
  File "/home/hwww/.local/lib/python3.6/site-packages/swift/Swift.py", line 159, in launch
    dev=self._dev,
  File "/home/hwww/.local/lib/python3.6/site-packages/swift/SwiftRoute.py", line 86, in start_servers
    inq.get(timeout=10)
  File "/usr/lib/python3.6/queue.py", line 172, in get
    raise Empty
queue.Empty

**Version information**

Did you install from PyPI or GitHub?
If PyPI what version number?  
PyPI  pip 21.3.1
If GitHub what commit hash?

Robotics Toolbox depends heavily on two other packages: Swift (3D graphics) and SpatialMath toolbox (underpinning maths utilities).  If you think your issue is related to these, then please answer the questions above for them.

**To Reproduce**
1. The shortest, complete, Python script that exhibits the bug.
2. The script output, including error messages.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Your OS (MacOS, Linux, Windows). ubuntu 18.04
- Your Python version.  python 3.6

**Additional context**

**Comment by WHuangEI** [comment]
How can I solve this, it is important for me.

**Comment by WHuangEI** [comment]
the version i checked:
swift -sim:1.0.0
spatialgeometry:1.0.1
spatialmath-python:1.0.5
PyPI pip 21.3.1
ubuntu 18.04, python 3.6

**Comment by WHuangEI** [comment]
@jhavl

**Comment by petercorke** [comment]
Sorry for the long wait getting back to you on this one.

This is a Python 3.6 incompatibility — `socketserver.SimpleHTTPRequestHandler`'s `directory=` keyword argument wasn't added until Python 3.7, and swift's server code has needed it since. Python 3.6 reached end-of-life in December 2021, and current roboticstoolbox/swift-sim both require a much newer Python (3.10+) — so this specific failure mode can't occur on any supported environment today.

Closing as an unsupported/obsolete environment issue. If you hit something similar on a current Python version, please open a fresh issue with the details.
