### ISSUE TITLE
Could not connect to swift simulator

### ISSUE THREAD

**Issue by WilliamBellemans** [petercorke/robotics-toolbox-python#421]
**Describe the bug**
I installed robotics toolbox from git, and I also installed Swift from git. If I try to use env.launch(), it says "Could not connect to Swift simulator"

**Version information**

I got the latest version from GitHub.

**To Reproduce**
![image](https://github.com/petercorke/robotics-toolbox-python/assets/142887212/7f6ad59a-8500-4cb1-9919-6508f5e78e39)
```
Could not connect to the Swift simulator

Traceback (most recent call last):
  File "/home/william/Robotics/test.py", line 7, in <module>
    env.launch()
  File "/home/william/swift/swift/Swift.py", line 172, in launch
    self.socket, self.server = start_servers(
  File "/home/william/swift/swift/SwiftRoute.py", line 166, in start_servers
    inq.get(timeout=10)
  File "/usr/lib/python3.10/queue.py", line 179, in get
    raise Empty
_queue.Empty
```
**Environment (please complete the following information):**
 - Ubuntu via WSL.
- Python 3.10

**Comment by rovalder** [comment]
Had the same issue with Ubuntu via WSL - downloading a browser in Ubuntu fixed the issue for me: 

```bash
sudo apt install firefox
```

**Comment by petercorke** [comment]
Thanks for the report, and sorry it took a while to circle back.

Looks like this was a WSL-specific environment issue rather than a toolbox bug — @rovalder's comment above nails it: swift needs an actual browser to open in, and a bare WSL Ubuntu install doesn't have one by default (`sudo apt install firefox` fixes it). Closing since this was answered in-thread; please reopen if installing a browser doesn't resolve it for you.
